### ISSUE TITLE
crash-report

### ISSUE THREAD

**Issue by TheDogmeat** [Chicken-Bones/EnderStorage#29]
Have a crash report for you.
I loged in on a single player map, relised i have the wrong map and log out and i had a crash to desctop.
http://pastebin.com/WWwVCDnE

**Comment by Andre-Maartens** [comment]
+1 same here

**Comment by Andre-Maartens** [comment]
+1 same here

**Comment by Lavaflow** [comment]
I have this same error (after attempting to update to a later version and then reverting, which may have caused it). I went into the game log and pulled this: http://pastebin.com/YnXPkq22

I think (but am not sure) that for some reason it thinks ender tanks are ender chests, so when it tries to find out what fluid is in it, it only sees spots for items, and freaks out.

I have also (once) used MCEdit to delete the one at the coordinates given in case it was a specific one that bugged out, but it happened again so it's a general thing. My client takes 5-10 minutes to start up (too many mods? No such thing!) and I have at a dozen ender tanks and at least twice as many ender chests in case I would need to delete those as well, and I really don't feel like spending that time.

**Comment by olee** [comment]
Same problem - also seen other people having the same problems already.
Any progress on this @Chicken-Bones ?

**Comment by Chicken-Bones** [comment]
Fixed 12ad77b208d88ec32bd7931e76a5e63e3e9ef945 (1.7.10-1.4.7.36)

**Comment by olee** [comment]
Sorry, but I am unable to find that version on http://chickenbones.net/Pages/links.html
