### ISSUE TITLE
Colors are Reversed when crafted

### ISSUE THREAD

**Issue by shadowfacts** [Chicken-Bones/EnderStorage#30]
@FireBall1725 found this on his stream, but when he crafted an ender tank in a crafting table with green, lime green, and red (in order left-to-right) the colors were displayed on the block itself as red, lime green, and green.

**Comment by Chicken-Bones** [comment]
Fixed 1a7dde93d3ca06fd71beed972db5eb26be90d107 (1.7.10-1.4.7.34)
