### ISSUE TITLE
endertank rendering crashes server

### ISSUE THREAD

**Issue by ProfDeCube** [Chicken-Bones/EnderStorage#37]
I've been making my own pack and everything else seems fine, whenever the endertank is rendered it crashes http://pastebin.com/ArM7tABY

**Comment by sci4me** [comment]
I think this is the one you have? http://pastebin.com/kVi3xUYe

This needs to be fixed! Seriously!

**Comment by Chicken-Bones** [comment]
Duplicate of #35
