### ISSUE TITLE
EnderTank Crashes On Render (Forge 10.13.3.1355+)

### ISSUE THREAD

**Issue by ethanbmnz** [Chicken-Bones/EnderStorage#39]
TL;DR You cannot use any EnderTank's On Forge 10.13.3.1355+ due to a render issue and then a crash.

How to reproduce:

Get Forge 10.13.3.1354 or below
Go into a world and get an ender tank
Place it in your hand - see it render
Place it down - see it render
Destroy the tank from both the world and your hand
Clear any NEI search
Get 10.13.3.1355 or above
Go into a world and try get an ender tank
Watch the game crash with render issues.

**Comment by Razorskills** [comment]
^ Thank you. I had to temporarily remove EnderStorage from my pack. Hopefully Chicken_bones can fix it

**Comment by Chicken-Bones** [comment]
Duplicate of #35
