### ISSUE TITLE
Please refer to RecipeSorter

### ISSUE THREAD

**Issue by RAnders00** [Chicken-Bones/EnderStorage#45]
`[12:53:15] [Client thread/INFO] [FML]:   Unknown recipe class! codechicken.enderstorage.common.EnderStorageRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter`

This does not crash the game, but is a warning spit out on game loading.

**Comment by Chicken-Bones** [comment]
Fixed 1a7dde93d3ca06fd71beed972db5eb26be90d107 (1.7.10-1.4.7.34)
