### ISSUE TITLE
Crash-report

### ISSUE THREAD

**Issue by yepidoodles** [Chicken-Bones/EnderStorage#46]
I updated my modpack and server today and when I go to look up endertanks/ chests in the creative menu, this happens:
https://www.dropbox.com/s/buh25ro6ucf0ozy/crash-2015-04-27_18.29.46-client.txt?dl=0

I updated:
Forge
Botania
Bibliocraft
Openmods
Openblocks

I've looked through the change logs of all the mods and I don't see anything effecting liquids, I'm at a loss at what is caused this, so any help would be great.
Thanks

**Comment by HanatakeYurii** [comment]
I had this error several times as well http://pastebin.com/f71Lb8CD
whatever I tried I didn't get rid of it yet
Running on Forge 1291 (not possible to change atm 'cause it's in a modpack)

**Comment by Chicken-Bones** [comment]
@yepidoodles Get the latest EnderStorage
@HanatakeYurii Get an older EnderStorage, or the latest forge

**Comment by HanatakeYurii** [comment]
Thanks,
Forgot to respond, took hours to find compatible CCC & EnderStorage with Forge 1352, but finally found & working well.

**Comment by Chicken-Bones** [comment]
sorry it took so long, latest of everything should work well
