### ISSUE TITLE
Crashs 

### ISSUE THREAD

**Issue by wandersonbraz** [Chicken-Bones/EnderStorage#47]
hello everyone

recently started to create a modpack to do some videos on youtube put all the mods that I liked list below and together with the storage ender 1 day or so my game comeceou the crashing updated the forge to the latest version with all mods and installed OPENEYE to see the mod that caused the crash and the crash log showing the storage ender.
is there any version that is not giving crash remembering that I have the forge and mods all the latest released version.

report
http://openeye.openmods.info/crashes/0c86443ca4db05538828ca844f7a3213

Mods
http://prntscr.com/70bmjq

translated into English in the google translator

**Comment by Chicken-Bones** [comment]
Grab the latest version

**Comment by wandersonbraz** [comment]
good day already used the recommended version and last on the site both are giving crash

**Comment by Chicken-Bones** [comment]
send me a full FML log with the latest version? (1.4.7.36)

**Comment by wandersonbraz** [comment]
I'm playing several hours a day with the 1.4.7.34 version and the core in version 1..3.4.16 until the moment not give any problem

**Comment by Chicken-Bones** [comment]
ok that's good
