### ISSUE TITLE
Private Enderchests are not private

### ISSUE THREAD

**Issue by Chaos234** [Chicken-Bones/EnderStorage#55]
Hey,

I like your mod but on my ftb infinity 1.5.0 server I can access all enderchest also the private ones. Please fix this because anybody can look into the chest and can steal some items even if the current player doesn't own the opened chest.

**Comment by Chicken-Bones** [comment]
That's intended. Private means no remote access, but like they say, if you have access to the hardware you win.

**Comment by Chaos234** [comment]
I can't believe your answer!

Vanilla Enderchest are instandly private and no one can see the content stored in there from another player nor can take out items from another player.

But your Enderchest do this so to set it private is actually wasting a diamond nothing more and nothing less.

Well, then I've to do it on my own way if you are thinking that the function of a vanilla enderchest can be disrupted by you.

Enderchests have allways be privat to the user who used the diamond on any public chest, so if I set a diamond on 5 chests, then only I should have access to it and if not then only the chestowner should tale out items from there.

You can change this very simple by useing a config-value so the user of the mod can change this to what they want but actually anybody can access the enderchest so you support grieving and this isn't to accpet!

I hope you change your mind!

**Comment by Chicken-Bones** [comment]
Consider them personal in stead of private. The idea is that no-one can accidentally or intentionally access your chest from a remote location. The current implementation is useful in that if you want to create a communication between only you and a few other players, you just put the diamond on all of them (or let them sync a pouch to your chest).

Why not just keep an EnderPouch in your inventory, or a locked chest. Or better yet, just hide your stuff :P
