### ISSUE TITLE
compatibility with EnderThing

### ISSUE THREAD

**Issue by Hypsellis** [Chicken-Bones/EnderStorage#73]
It would be nice if EnderStorage is compatible with EnderThing. http://minecraft.curseforge.com/projects/enderthing

**Comment by Ecu** [comment]
No.  While I was the one to have Ender Storage become open source, I still don't condone the practice of blatantly copying an existing mod in the community.  Especially when the mod being copied is still being supported.  

Enderthing is quite obviously a clone of my mod and as such I see no reason to offer compatibility.
